# Generated by Django 2.0.5 on 2018-05-04 21:29

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Case',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('case_title', models.CharField(max_length=100)),
                ('time_posted', models.DateTimeField(auto_now_add=True)),
                ('case_text', models.CharField(max_length=600)),
            ],
        ),
    ]
