# Generated by Django 2.0.5 on 2018-05-04 22:15

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('cases', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='case',
            old_name='case_text',
            new_name='text',
        ),
        migrations.RenameField(
            model_name='case',
            old_name='case_title',
            new_name='title',
        ),
    ]
