# Generated by Django 2.0.5 on 2018-05-08 23:23

from django.db import migrations
import tinymce.models


class Migration(migrations.Migration):

    dependencies = [
        ('cases', '0003_case_author'),
    ]

    operations = [
        migrations.AlterField(
            model_name='case',
            name='text',
            field=tinymce.models.HTMLField(),
        ),
    ]
