# Generated by Django 2.0.5 on 2018-05-11 04:15

import cases.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cases', '0006_rawfile'),
    ]

    operations = [
        migrations.AlterField(
            model_name='case',
            name='text',
            field=models.CharField(max_length=4000),
        ),
        migrations.AlterField(
            model_name='rawfile',
            name='file',
            field=models.FileField(upload_to=cases.models.user_directory_path, validators=[cases.models.validate_file_extension]),
        ),
    ]
