# Generated by Django 2.0.5 on 2018-05-11 07:18

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('cases', '0007_auto_20180511_0415'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='casefile',
            name='tags',
        ),
    ]
